services:
  app:
    build:
      context: .
    container_name: go_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=sumit
      - DB_PASSWORD=sumit05
      - DB_NAME=patiently

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: sumit
      POSTGRES_PASSWORD: sumit05
      POSTGRES_DB: patiently
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
